[tool.poetry]
name = "akipy"
version = "0.1.2"
description = "A Python library wrapper for Akinator"
authors = ["advnpzn <adenosinetp10@protonmail.com>"]
readme = "README.md"
repository = "https://github.com/ufoptg/akipy"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.9.2"
httpx = "^0.28.1"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ufoptg/akipy/issues"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
